### ISSUE TITLE
(Feature) Text captcha solving

### ISSUE THREAD

**Issue by ja3abuser** [Wikidepia/hektCaptcha-extension#1]
Hello! Thank you for your work :) It works, but the extension has to be unzipped, otherwise you won't be able to install it. 
It would be really nice to add a text captcha solution for a given image selector and input field.

**Comment by Wikidepia** [comment]
Hi, thanks for testing it!

> And for some reason HCaptcha is solved with 5-6 times, maybe it is because of the model or maybe it is because there is no delay between clicking on the image.

Yes I will add delay very soon

> It would be really nice to add a text captcha solution for a given image selector and input field.

I dont think I will add support for text captcha anytime soon :(
