### ISSUE TITLE
UPDATE speclass.json

### ISSUE THREAD

**Issue by D4RKSCR1PTS** [Wikidepia/hektCaptcha-extension#110]
{
    "Please click on each image containing the smallest animal.": "NESTED_CLASSIFY",
    "Please click on each image containing the largest animal.": "NESTED_CLASSIFY",
    "Please click on the largest animal.": "NESTED_CLASSIFY",
    "Please click on each image containing the smallest animal in real life": "NESTED_CLASSIFY"
    "Please click on each image containing the largest animal in real life": "NESTED_CLASSIFY"
}

There's no comma on smallest animal in real life...

**Comment by anoleido** [comment]
This can be solve by edit the hcaptcha.js from .zip with this. 


const h={"Please click on each image containing the smallest animal.":"NESTED_CLASSIFY","Please click on each image containing the largest animal.":"NESTED_CLASSIFY","Please click on the largest animal.":"NESTED_CLASSIFY","Please click on each image containing the smallest animal in real life":"NESTED_CLASSIFY","Please click on each image containing the largest animal in real life":"NESTED_CLASSIFY"};s=[a]||h;


This will pass on this error, but the models for solving is  not updated for over 3 weeks. It will refresh every time.

**Comment by Wikidepia** [comment]
Fixed
