### ISSUE TITLE
struggling with basketball hcaptcha

### ISSUE THREAD

**Issue by yakuzas2345** [Wikidepia/hektCaptcha-extension#19]
hi .. first , the AI works very well but on some captcha i never get success .. is it possible to add a function for the AI autolearning ? .. like this the more he does a certain captcha the more he master it .. thanks

**Comment by Wikidepia** [comment]
Hi, please screenshot your hcaptcha that failed

**Comment by Wikidepia** [comment]
Model already updated, please reopen if basketball accuracy is still low
