### ISSUE TITLE
extension can not install

### ISSUE THREAD

**Issue by HkerVit** [Wikidepia/hektCaptcha-extension#2]
please fix install on chrome extension

**Comment by HkerVit** [comment]
File
~/Desktop/hektCaptcha-extension-0.1.1
Error
Manifest file is missing or unreadable
Could not load manifest.

**Comment by Wikidepia** [comment]
Please use the newest version and follow installation instruction.

How to use:

- Download the latest .crx file
- Unzip it to a folder
- Open chrome://extensions/ in Chrome
- Enable Developer mode
- Click Load unpacked and select the folder
