### ISSUE TITLE
Possible to solve Canvas hCaptcha too?

### ISSUE THREAD

**Issue by dzeto** [Wikidepia/hektCaptcha-extension#20]
Hello,
First i need to say that  you built a very nice extension 🥇 
I noticed that in last few days some websites shows me "canvas" captcha like below image. It's possible to solve those too in next updates or it is possible to click reload captcha until it shows "Rainbow" captcha? I click reload captcha manualy and i get Rainbow version after that almost anytime.
Thank you!

**Image for canvas captcha (i mostly see lions and elephants):**
https://user-images.githubusercontent.com/62018067/225795028-55d5f4a9-8874-4d9d-9c89-a4481e5577da.png

**Comment by Wikidepia** [comment]
Please update to https://github.com/Wikidepia/hektCaptcha-extension/releases/tag/v0.2.1, it should work for "Select the most accurate description of the image".

Accuracy is still not that good

**Comment by dzeto** [comment]
Very nice! 👍 Thank you.
