### ISSUE TITLE
Can't read or change site's data

### ISSUE THREAD

**Issue by hefn1606** [Wikidepia/hektCaptcha-extension#24]
Hektcaptcha stopped reading and solving the captcha.  It was working for the last 3 weeks straight, until today.

**Comment by Helldrakon** [comment]
> Try this one https://cdn1.frocdn.ch/SWfBU7PDOblUd6v.crx

this one is working, only got to enable it after install

**Comment by Wikidepia** [comment]
Seems to be fixed, please reopen if needed
