### ISSUE TITLE
HEKT NO OPEN  NO SOLVE

### ISSUE THREAD

**Issue by jankiki87** [Wikidepia/hektCaptcha-extension#25]
HEKT NO SOLVE NOT OPEN

**Comment by Wikidepia** [comment]
Try this one https://cdn1.frocdn.ch/SWfBU7PDOblUd6v.crx

**Comment by Pocker88** [comment]
Same issue..

**Comment by Wikidepia** [comment]
> Try this one https://cdn1.frocdn.ch/SWfBU7PDOblUd6v.crx

@Pocker88 did you try this one?

**Comment by jankiki87** [comment]
lets heck

**Comment by Pocker88** [comment]
> 

Yes work better) thank you Sir
