### ISSUE TITLE
even if you refresh the page

### ISSUE THREAD

**Issue by uzi98f** [Wikidepia/hektCaptcha-extension#26]
![image](https://user-images.githubusercontent.com/125817798/230262030-1d5bcbe5-28c2-4c80-996b-fa342b4255dc.png)

now the hcaptcha appears more often in this way, It doesn't matter if you refresh the page

 using the last version 0.2.5

**Comment by Wikidepia** [comment]
hektCaptcha does not support canvas captcha for now.
