### ISSUE TITLE
Can you add this extension in the firefox addon too? please :)

### ISSUE THREAD

**Issue by XShouko** [Wikidepia/hektCaptcha-extension#29]

**Comment by xHyroM** [comment]
@Wikidepia pleaseee

**Comment by XShouko** [comment]
@Wikidepia Pleaseeeee Pleaseeee

**Comment by xHyroM** [comment]
i'm trying to do this but i'm stucked on chrome-extension:// because idk what firefox, mozilla have

**Comment by sopogit** [comment]
Anyone find a way to use this on firefox?

**Comment by Wikidepia** [comment]
It seems that onnxruntime-web does not do well with firefox, I have tried to port it today and got weird error

**Comment by sopogit** [comment]
> It seems that onnxruntime-web does not do well in firefox, I have tried to port it today and got weird error
> 
> EDIT: nvm, i forgot to edit wasm paths. there will be firefox support soon!

Hello, when will it be available?

**Comment by Wikidepia** [comment]
> > It seems that onnxruntime-web does not do well in firefox, I have tried to port it today and got weird error
> > EDIT: nvm, i forgot to edit wasm paths. there will be firefox support soon!
> 
> Hello, when will it be available?

Hopefully next week, firefox extension review is very slow

**Comment by Wikidepia** [comment]
If anyone wanted to test firefox extension:

https://cdn1.frocdn.ch/fk3fdQBXwALuNgA.xpi

**Comment by sopogit** [comment]
> If anyone wanted to test firefox extension:
> 
> https://cdn1.frocdn.ch/fk3fdQBXwALuNgA.xpi

I just tested it and it's working perfect, thanks

**Comment by letangminh** [comment]
> > If anyone wanted to test firefox extension:
> > https://cdn1.frocdn.ch/fk3fdQBXwALuNgA.xpi
> 
> I just tested it and it's working perfect, thanks

What version of Firefox are you running on? My latest firefox 114.0 (64 bits) doesnt work with this addon

**Comment by sopogit** [comment]
> > > If anyone wanted to test firefox extension:
> > > https://cdn1.frocdn.ch/fk3fdQBXwALuNgA.xpi
> > 
> > 
> > I just tested it and it's working perfect, thanks
> 
> What version of Firefox are you running on? My latest firefox 114.0 (64 bits) doesnt work with this addon

Im running firefox version 114.0 (64-bit)
