### ISSUE TITLE
will you add support for this captcha 

### ISSUE THREAD

**Issue by Raroll** [Wikidepia/hektCaptcha-extension#31]
Hey i wonder if you're going to add support for this type of captcha
![image](https://user-images.githubusercontent.com/94701898/233224560-0589ca18-9e84-469c-a631-119bcab9526f.png)

**Comment by Wikidepia** [comment]
There will be update soon

**Comment by Pocker88** [comment]
> There will be update soon

Mega Thank you for your help and work!!!! Grateful thank you 🙏

**Comment by Wikidepia** [comment]
Now supported, please use https://github.com/Wikidepia/hektCaptcha-extension/releases/tag/v0.2.7b1

**Comment by Raroll** [comment]
BRH ITS INSANE Keep up good work ggggggggg

**Comment by alvaradolisandro** [comment]
https://accounts.hcaptcha.com/demo?sitekey=195eeb9f-8f50-4a9c-abfc-a78ceaa3cdde
