### ISSUE TITLE
Some captchas arent supported

### ISSUE THREAD

**Issue by Damnbuoy** [Wikidepia/hektCaptcha-extension#33]
🙂Thank you so much for making this extension it means alot to me :D

Bee flying near a flower and Computer keyboard, both of them are super annoying as sometimes they refresh in infinite loop :(

![Screenshot_20230429-173148_Discord](https://user-images.githubusercontent.com/115924892/235301988-159be3db-d4de-4bd3-89fc-5842a36dc17d.jpg)
![Screenshot_20230429-173215_Discord](https://user-images.githubusercontent.com/115924892/235301992-9f6b57a4-e1c5-40ea-8935-498e2e28d7e7.jpg)

**Comment by Wikidepia** [comment]
Should be supported now

**Comment by Damnbuoy** [comment]
thank you sooo muchhh!!!!!!!!!
