### ISSUE TITLE
Thank you and for your efforts 

### ISSUE THREAD

**Issue by b12b12** [Wikidepia/hektCaptcha-extension#38]
I have a problem I have to switch my browser to english for it to work recaptch and hcaptcha 
I hope to solve this problem

**Comment by Serega007RU** [comment]
It looks like it's a duplicate of #36

**Comment by Pocker88** [comment]
😅

**Comment by alvaradolisandro** [comment]
https://accounts.hcaptcha.com/demo?sitekey=195eeb9f-8f50-4a9c-abfc-a78ceaa3cdde   
this challenge is not solved by the extension

**Comment by alvaradolisandro** [comment]
https://accounts.hcaptcha.com/demo?sitekey=195eeb9f-8f50-4a9c-abfc-a78ceaa3cdde
this challenge is not solved by the extension

**Comment by Wikidepia** [comment]
Hi, please do not spam. I can read it already :)

**Comment by Wikidepia** [comment]
Closed, duplicate #36
