### ISSUE TITLE
failed to fetch using proxies

### ISSUE THREAD

**Issue by ciaaddicted** [Wikidepia/hektCaptcha-extension#39]
Hello, I see that you are using cloudflare cdn to share ORT models, but cloudflare does not like requests using proxy and challenging them using js challenge. Can you create a custom rule in cloudflare to skip it?

Security -> WAF -> Create rule -> 
<img width="1071" alt="image" src="https://github.com/Wikidepia/hektCaptcha-extension/assets/133263947/b06880b7-19cb-42f2-90f2-67b664adb957">

**Comment by Serega007RU** [comment]
You can try in your proxy settings to add to the exceptions the site where ORT models are located

**Comment by Wikidepia** [comment]
I have added it to cloudflare, thanks!
