### ISSUE TITLE
How to build your project?

### ISSUE THREAD

**Issue by Serega007RU** [Wikidepia/hektCaptcha-extension#40]
Hello, I want to make a Pull Request, but I simply can't build your project, I get this error
```
"C:\Program Files\nodejs\npm.cmd" run build

> hektcaptcha-extension@0.3.0.1 build
> webpack --mode=production --config config/webpack.config.js

assets by status 4.78 MiB [cached] 15 assets

ERROR in ./src/hcaptcha.js 17:12-38
Module not found: Error: Can't resolve 'onnxruntime-web' in 'D:\Developments\ChromeExtensions\Captcha\hektCaptcha-recaptcha\src'        

ERROR in ./src/recaptcha.js 17:12-38
Module not found: Error: Can't resolve 'onnxruntime-web' in 'D:\Developments\ChromeExtensions\Captcha\hektCaptcha-recaptcha\src'        

ERROR in unable to locate 'D:/Developments/ChromeExtensions/Captcha/hektCaptcha-recaptcha/node_modules/onnxruntime-web/dist/*.wasm' glob

2023-05-14 21:57:03: webpack compiled

Process finished with exit code 1
```
Unfortunately, I'm not very strong in NodeJS and I can't fix this error on my own.

**Comment by Fer010** [comment]
@Serega007RU I was able to build it by changing the "onnxruntime-web" package from "file:onnxruntime-web-minimal" to the version "^1.14.0". This should do the trick:

```
npm uninstall onnxruntime-web
npm i onnxruntime-web

```

But, I don't know if this approach might be missing something up.

@Wikidepia do you mind sharing some insight about this pkg? Is file:onnxruntime-web-minimal' a customized version of it?
Sorry for the newbie question, but everything related to onnx and py training is new to me.

**Comment by Wikidepia** [comment]
I will update later

**Comment by Wikidepia** [comment]
Should be available now
