### ISSUE TITLE
Recaptcha V2 y@hoo login !

### ISSUE THREAD

**Issue by scrollbusiness** [Wikidepia/hektCaptcha-extension#43]
recaptcha not working on y@hoo login page, please check !

**Comment by Serega007RU** [comment]
in manifest.json on line 40 replace
```
      "matches": ["*://*.google.com/recaptcha/api2/*"],
```
to
```
      "matches": ["*://*.google.com/recaptcha/api2/*", "*://*.google.com/recaptcha/enterprise/*"],
```

this will help solve your problem, but the author of the extension should do the same

**Comment by scrollbusiness** [comment]
Thaaaaaaaaaaaaank you so much dude very helpful :) !
