### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by om91qq** [Wikidepia/hektCaptcha-extension#5]
I run `npm install` and then `npm run build` which shows the following error:

```
> hektcaptcha-extension@0.1.3 build
> webpack --mode=production --config config/webpack.config.js

assets by status 581 KiB [cached] 10 assets

ERROR in ./src/contentScript.js 15:12-38
Module not found: Error: Can't resolve 'onnxruntime-web' in '/tmp/hektCaptcha-extension/src'

ERROR in unable to locate '/tmp/hektCaptcha-extension/node_modules/onnxruntime-web/dist/*.wasm' glob

2023-01-30 16:41:29: webpack compiled
```

**Comment by Pocker88** [comment]
![Uploading Screenshot_2023-01-31-12-35-30-96_4d38fce200f96aeac5e860e739312e76.jpg…]()

**Comment by neerajrk2509** [comment]
I am getting the same error but while installing packages.

**Comment by Wikidepia** [comment]
Hi, I will upload onnxruntime-web minimal later

**Comment by Pocker88** [comment]
Hello Wikipedia Admin, can you add new set pictures in your solver extension?!

**Comment by Wikidepia** [comment]
Updated, please `git pull` and try to build again
