### ISSUE TITLE
Can't solve traffic lights and fire hydrants on 4x4

### ISSUE THREAD

**Issue by Serega007RU** [Wikidepia/hektCaptcha-extension#52]
On version 0.3.0.2, hektCaptcha can't solve traffic lights and fire hydrants on 4x4, it just clicks skip.

There is no such problem on version 0.3.0.1.

Maybe he can't solve something else, reCAPTCHA gives me only buses, stairs, motorcycles, bicycles, traffic lights and fire hydrants on 4x4, other options I don't come across

If traffic lights and fire hydrants come across in 3x3, there he can solve

![image](https://github.com/Wikidepia/hektCaptcha-extension/assets/64780091/7d0cb6dc-faad-49fd-bad6-71838907b4bd)

**Comment by Wikidepia** [comment]
Yeah, there seems to be bug when normalizing labels. Will look into it later
