### ISSUE TITLE
Thanks , working good but ...

### ISSUE THREAD

**Issue by bettonna** [Wikidepia/hektCaptcha-extension#55]
Hi bro thanks for that addon , it's good working, but it doesn't work background , We need to focus that page for solving hcaptca, if we doesn't page it's not solving hcaptcha, ( I mean , I'm opening a hcaptcha page and later I'm going other pages and it's not working, need focus and wait that hcaptcha page,  if I open a hcaptcha page I'm waiting and focus this page yes it's working but without focus and no wait that page not working ), Can you fix it please?? and Can you release newest versions for  Firefox please??? Thanks , Have a good day

**Comment by Wikidepia** [comment]
Duplicate #53. I will try to fix later
