### ISSUE TITLE
 Can it be prevented from automatically reloading?

### ISSUE THREAD

**Issue by sol32ok** [Wikidepia/hektCaptcha-extension#59]
Hello friend, the extension is excellent.. but I find something that frustrates me a bit, I hope you can help me... When the AI ​​does not know how to make the new hc, examples are the new selection hc, it automatically starts reloading the hcaptchas until it finds one that recognizes, how would I make it so that it does not reload the hcaptchas... but if it does not know how to do it, I leave it like that and I do it manually... I have seen that it learns the extension quickly, what it does not know how to do one day, the next day He learns it... but if he doesn't let me teach him, it's hard for him to learn if when he doesn't know how to do something, he automatically reloads... Is there a solution so that he doesn't just recharge when he doesn't know something, it stays static and I do it manually.. It is that if it recharges too much, they ban me from the website where I try to enter.

**Comment by ko19sty** [comment]
I also faced this problem when novy vybor hc came out, I can't solve the captcha, please fix

**Comment by Wikidepia** [comment]
You can add delay before reloading now
