### ISSUE TITLE
Dear Admin can you help..

### ISSUE THREAD

**Issue by Pocker88** [Wikidepia/hektCaptcha-extension#6]
New pictures in Hcaptcha..
![215747061-2a2bf335-a70e-4b65-a86c-1643270905d3](https://user-images.githubusercontent.com/79075067/216040976-41b4aeb5-f529-476e-87de-ae6faacf14d5.jpg)

**Comment by Wikidepia** [comment]
Thanks to QIN2DIM, forest class is now available
