### ISSUE TITLE
Delay when not able to solve

### ISSUE THREAD

**Issue by Goswinus** [Wikidepia/hektCaptcha-extension#67]
If the (BTW extremely useful and excellent) extension does not know how to solve a particular puzzle, it reloads the puzzle until it finds a puzzle that it _can_ solve. This refresh is done as fast as it can. 

If I am at the keyboard at that particular moment, I would like to be able to "manually" solve the puzzle.

My suggestion would be to add a "Reload timer" to the configuration. If I put "10000" in that field, it would give me 10 seconds to manually solve an unsupported puzzle. If I haven't solved it, the extension can still refresh and try again.
The delay is also a nice gesture to hCaptcha (reduce the number of reloads)...

As a bonus: You might even use the entered manual solution to train your AI for puzzles that you haven't been able to solve yet :)

**Comment by Waifubasics** [comment]
> Good idea, might implement later

hi bro im trying to change the deley time on the new update but it keeps reverting back to 500MS

**Comment by Wikidepia** [comment]
there is bug in menu, but it still works

**Comment by Waifubasics** [comment]
it cant solve this one
![image](https://github.com/Wikidepia/hektCaptcha-extension/assets/139308453/88c0779d-111e-4f15-a445-172e0b9e9546)
