### ISSUE TITLE
Bad guessing raccoon!

### ISSUE THREAD

**Issue by softweri** [Wikidepia/hektCaptcha-extension#71]
Bad guessing raccoon!
Correct if possible.
![image](https://github.com/Wikidepia/hektCaptcha-extension/assets/5292472/27e531dd-3f46-4e48-b728-f75a5cbc0653)

**Comment by privacyguy123** [comment]
its terrible with oranges too ...

**Comment by anoleido** [comment]
They dont have enough data yet, wait

**Comment by Wikidepia** [comment]
I will try to update it today
