### ISSUE TITLE
problem with new hcaptcha images

### ISSUE THREAD

**Issue by JosueeHzP** [Wikidepia/hektCaptcha-extension#72]
does not solve the number hcaptcha, add the recaptcha extension to firefox please

https://github.com/Wikidepia/hektCaptcha-extension/assets/101265389/d018d337-dcf2-49a0-9b09-e24dc59eb369
https://github.com/Wikidepia/hektCaptcha-extension/assets/101265389/b12bd89f-1b8f-4084-bacc-a607544d9f7d
https://github.com/Wikidepia/hektCaptcha-extension/assets/101265389/7402d107-3220-45df-aa4b-cd51f76c682a
https://github.com/Wikidepia/hektCaptcha-extension/assets/101265389/e0fe4fb3-eff2-404b-a233-672fcdf0261a
https://github.com/Wikidepia/hektCaptcha-extension/assets/101265389/0610c7b9-e8fb-4a95-be55-db466aa9d253

**Comment by Beautiful-Gallery** [comment]
sir please update all hcaptcha new images

**Comment by anoleido** [comment]
They dont have enough data yet, wait
