### ISSUE TITLE
PLEASE TRY TO UPDATE YOUR RECAPTHA AND HCAPTCHA 

### ISSUE THREAD

**Issue by Beautiful-Gallery** [Wikidepia/hektCaptcha-extension#75]
YOUR EXTENSION MADE SO MANY MISTAKES IN SOLVING CAPTCHAS AND SKIP MOST OF THE CAPTCHAS IN RECAPTCHA AND HCAPTCHA BOTH

SORRY FOR MY BAD ENGLISH I HOPE U UNDERSTAND

**Comment by AMEERTYPING** [comment]
update

**Comment by AMEERTYPING** [comment]
how i can i insert captcha solver

**Comment by AMEERTYPING** [comment]
how i can fix it
