### ISSUE TITLE
Error in extension.

### ISSUE THREAD

**Issue by neerajrk2509** [Wikidepia/hektCaptcha-extension#8]
I was taking look at the extension and found that it was throwing some errors.
<img width="693" alt="image" src="https://user-images.githubusercontent.com/59948556/216800477-0e4eb0d6-ed8f-4a20-adf3-4215e8e851ad.png">
Can you please take a look at this?

**Comment by Wikidepia** [comment]
This occurs when the extension is unable to solve the captcha because the model does not yet exist (cannot be solved), so it will reload to obtain another captcha.
