### ISSUE TITLE
Recaptcha 3x3 not work at all on 3.0b3

### ISSUE THREAD

**Issue by zodiacc7** [Wikidepia/hektCaptcha-extension#86]
Recaptcha 3x3 not work at all on 3.0b3

**Comment by Wikidepia** [comment]
I am currently moving models around, there will be update hopefully tomorrow

**Comment by FMDose89** [comment]
Pls Sir fix this

**Comment by Wikidepia** [comment]
There is new version you can try it: https://github.com/Wikidepia/hektCaptcha-extension/releases/tag/v0.3.0
