### ISSUE TITLE
can't load unpacked extention using crx in brave

### ISSUE THREAD

**Issue by bugbounted** [Wikidepia/hektCaptcha-extension#9]
Hi [Akmal](https://github.com/Wikidepia),
I'm trying to install extention on my brave but can't do it because brave haven't any flag for enforce extenral extention trustable .
waiting for your response
finest regards

**Comment by Fer010** [comment]
You could try extracting the content to a folder with 7zip or any compression tool that can handle it, and then load it using the 'Load unpacked' button in Brave.

**Comment by Wikidepia** [comment]
Hi bugbounted, I've never tried the extension in Brave but you could try to load unpacked extension. I'm also planning to add this extension chrome web store, you could wait for it.

**Comment by Wikidepia** [comment]
hektCaptcha is now available in chrome web store

https://chrome.google.com/webstore/detail/hektcaptcha-hcaptcha-solv/bpfdbfnkjelhloljelooneehdalcmljb?hl=en
