### ISSUE TITLE
Help with hekt model

### ISSUE THREAD

**Issue by D4RKSCR1PTS** [Wikidepia/hektCaptcha-extension#90]
how do I train it and where does it get the images from?

**Comment by Wikidepia** [comment]
Training notebook is available here: https://github.com/Wikidepia/hektCaptcha-model, I have not update it to the new model yet (maybe later). I get images from hcaptcha directly

**Comment by D4RKSCR1PTS** [comment]
Thank you. One more thing, could you give me the code you use to give users ort files from akmal.dev? I'm trying to make a hcaptcha solving API but for free.
