### ISSUE TITLE
akmal.dev

### ISSUE THREAD

**Issue by D4RKSCR1PTS** [Wikidepia/hektCaptcha-extension#91]
Thank you. One more thing, could you give me the code you use to give users ort files from https://akmal.dev? I'm trying to make a Hcaptcha solving API but for free. Thank you in advance for your consideration.

edit: I need this code because I'm using a storage server that could run the code, then another server can make a request to it to get the ort file.

**Comment by Wikidepia** [comment]
It should be here: https://github.com/Wikidepia/hektCaptcha-extension/blob/d08087d36f9241119e642f2d4d410247990b6b07/src/hcaptcha.js#L381-L395

**Comment by D4RKSCR1PTS** [comment]
> It should be here:
> 
> https://github.com/Wikidepia/hektCaptcha-extension/blob/d08087d36f9241119e642f2d4d410247990b6b07/src/hcaptcha.js#L381-L395

I was referring to the code behind akmal.dev, if you feel like sharing that. sorry if that's rude, I just don't know what I'm doing. Thank you.
